### ISSUE TITLE
feat: autoscale base on number of requests

### ISSUE THREAD

**Issue by parano** [bentoml/Yatai#154]
Currently Yatai implements an auto-scaling strategy based on CPU utilization, however it is not applicable in many ML model deployment use cases(e.g. a GPU runner or an IO-intensive Runner that does feature fetching). An alternative is to allow user to set an object metrics, using for example:

* autoscale base on  a target `requests-per-second` limit
* autoscale base on  a target `number-of-requests` over a period of time that is configurable by the users. e.g. number of request per 2 minutes.
* autoscale base on a `number-of-requets-in-backlog` limit.

**Comment by ktoulgaridis** [comment]
Instrumentation aside, to begin with it could be allowed to configure the metrics object like this consuming any custom metric. 
```yaml
metrics:
  - type: Pods
    pods:
      metric:
        name: <MY_CUSTOM_METRIC>
      target:
        type: MyType
        myType: myTypeValue
```
