### ISSUE TITLE
feat: configurable autoscaling behavior

### ISSUE THREAD

**Issue by parano** [bentoml/Yatai#155]
Yatai deployment should allow advanced users to configure and fine-tune its auto-scaling behavior. A good starting point is to allow propagating related configurations to Horizontal pod autoscaler, e.g.:

```
behavior:
  scaleDown:
    stabilizationWindowSeconds: 300
    policies:
    - type: Percent
      value: 100
      periodSeconds: 15
  scaleUp:
    stabilizationWindowSeconds: 0
    policies:
    - type: Percent
      value: 100
      periodSeconds: 15
    - type: Pods
      value: 4
      periodSeconds: 15
    selectPolicy: Max
```
