### ISSUE TITLE
feat: declarative deployment management for GitOps workflow on Yatai

### ISSUE THREAD

**Issue by parano** [bentoml/Yatai#159]
This is something from our original design for Yatai but still missing in the current implementation. We would want to allow users to describe a deployment's detailed spec via a YAML file, which guarantees reproducing an identical model deployment on Kubernetes.  This is especially useful for a GitOps workflow, where user can test out a deployment in test/dev environment, check in the YAML file to git repo, and apply the same deployment config to production cluster.

1. DevOps centric workflow with kubectl and Kubernetes CRD resource config:

```bash
kubectl apply ./bento_deployment.yaml
```

```yaml
# bento_deployment.yaml
apiVersion: yatai.bentoml.org/v1beta1
kind: BentoDeployment
metadata:
  ...
spec:
	bento_tag: 'fraud_detector:dpijemevl6nlhlg6'
	autoscaling:
	  minReplicas: 3
	  maxReplicas: 20
	resources:
		limits:
			cpu: 500m
		requests:
			cpu: 200m
	runners:
		model_runner_a:
			autoscaling:
				minReplicas: 1
				maxReplicas: 5
			resources:
				limits:
					nvidia.com/gpu: 1
					cpu: 2000m
				...
```

Note: we will not provide a `bentoml yatai` CLI command for creating/updating/deleting deployments for now. This is something we could potentially provide in the future. The benefit of it is that if a team wants its ML team to manage deployments, DevOps don't need to worry about each ML scientists' k8s cluster access, they only manage Yatai's service role permissions & quota, and Yatai will handle the API token management within ML team. 
```bash
bentoml yatai deploy -f ./my_deployment.yaml --cluster default --yatai-context default
```
