### ISSUE TITLE
Components, operators and builders resources not created when installing Yatai with postgresql.enabled=false

### ISSUE THREAD

**Issue by amelki** [bentoml/Yatai#205]
When I install Yatai using the following values:

```yaml
postgresql:
  enabled: false

externalPostgresql:
  host: <my RDS host>
  port: 5432
  user: <my username>
  password: <my password>
  database: yatai
```

none of the resources that should be created in components, operators and builders are created.
If I comment `postgresql.enabled` and reinstall (after having deleted all Yatai resources), then all components get created.
I can then upgrade with `postgresql.enabled = false`.

I tried the operation many times and consistently got the issue

Do you confirm the issue ? Am I missing something ?
