### ISSUE TITLE
Cannot reach Yatai console if ingress class name is yatai-ingress

### ISSUE THREAD

**Issue by amelki** [bentoml/Yatai#211]
With the default Yatai helm install and the following values, the URL http://yatai.dev.mydomain.com gives me a 404
```
yatai:
  ingress:
    hosts:
      - host: yatai.dev.mydomain.com
        paths:
```

If I reinstall and override the `yatai-ingress` class name:
```
yatai:
  ingress:
    className: nginx
    hosts:
      - host: yatai.dev.paretos.com
        paths:
```
then it's fine, I can see the Yatai console login page.

Am I missing something ?
