### ISSUE TITLE
Yatai UI not showing deployments done via kubectl command

### ISSUE THREAD

**Issue by pi194046** [bentoml/Yatai#290]
I have performed yatai installation with external minio storage and external private docker registry
I am able to upload bento and models to console and observed it on the UI
however when I perform bento deployment using kubectl command I an unable to see it on the UI
only if I create the deployment from console can I see it reflected on the UI

Below is deployment file I am using

```
apiVersion: serving.yatai.ai/v1alpha2
kind: BentoDeployment
metadata:
  name: f2
  namespace: yatai
spec:
  autoscaling:
    max_replicas: 1
    min_replicas: 1
  bento_tag: onnx_vad:vdrgpiqjxcuw2pko
  envs: []
  ingress:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 500Mi
  runners:
  - autoscaling:
      max_replicas: 1
      min_replicas: 1
    envs: []
    name: onnx_vad
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 500Mi

```
