### ISSUE TITLE
Yatai v1 deploy error

### ISSUE THREAD

**Issue by fortunto2** [bentoml/Yatai#340]
Hi, trying deploy model to Yatai in Google Cloud Kubernetes 

GKE 1.23.8-gke.1900 
bentoml, version 1.0.5
bentoctl, version 0.3.3
yatai v1.0.0-a0-c311e4d

Create Yatai with command:
```
DEVEL=true bash <(curl -s "https://raw.githubusercontent.com/bentoml/yatai/main/scripts/quick-install-yatai.sh")

```

Upload model and bento 100%
But when create model from UI, get error

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1236751/189940472-8d67cba3-5540-4b92-aafc-e864f1e533ff.png">

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/1236751/189938582-52152acd-e1bc-4010-beaa-1d3a92e546eb.png">

```
failed to solve: failed to read dockerfile: failed to mount /home/user/.local/tmp/buildkit-mount1911555301: [{Type:bind Source:/home/user/.local/share/buildkit/runc-native/snapshots/snapshots/1 Options:[rbind ro]}]: operation not permitted
```

when manualy  `helm upgrade --install cryptospam -n yatai -f cryptospam_deployment.yaml`

```
apiVersion: serving.yatai.ai/v1alpha2
kind: BentoDeployment
metadata:
    name: cryptospam
    namespace: services
spec:
    bento_tag: spam_classifier:5he3tlbrcgfhwhqa
    ingress:
        enabled: true
    resources:
        limits:
            cpu: "500m"
            memory: "2Gi"
        requests:
            cpu: "250m"
            memory: "512m"
    runners:
        - name: runner1
          resources:
              limits:
                  cpu: "1000m"
                  memory: "2Gi"
              requests:
                  cpu: "500m"
                  memory: "512m"


```

kubectl get events -n services

```
Failed to fetch Bento spam_classifier:5he3tlbrcgfhwhqa: DoJsonRequest Error: [GET]http://yatai.yatai-system:80/api/v1/bento_repositories/spam_classifier/bentos/5he3tlbrcgfhwhqa: GET http://yatai.yatai-system:80/api/v1/bento_repositories/spam_classifier/bentos/5he3tlbrcgfhwhqa status=403, 

{"message":"get api token: record not found"}
```

<img width="996" alt="image" src="https://user-images.githubusercontent.com/1236751/189941173-e3acd4a4-9837-410a-b50d-09f42f398b1f.png">

whats wrong?
