### ISSUE TITLE
Deploy a "custom Bentoml image" using "yatai-deployment" instead of using "yatai-image-builder".

### ISSUE THREAD

**Issue by tonylauCN** [bentoml/Yatai#483]
"Yatai" is a great project, and my team started using it since version "1.0.0a7" and it's fine. However, recently, we updated the versions of Yatai components:
```yaml
yatai 1.1.9
yatai-deployment 1.1.13
yatai-image-builder 1.1.8
```
After the update, we encountered issues with the deployment. Here are the specific details:

We use custom jobs to build Bentoml images (still using the Bentoml commands):

```bash
bentoml build ..
bentoml containerize ..
docker login ..
docker tag ..
docker push ..
bentoml yatai login ..
bentoml push ..
```

After these steps, we create a CRD file for deployment:

```yaml
apiVersion: serving.yatai.ai/v2alpha1
kind: BentoDeployment
metadata:
  name: {{.name}}
  namespace: {{.namespace}}
spec:
  bento: {{.bentoTag}}
  extraPodMetadata:
    labels:
      name: {{.name}}
      startTime: "{{.startTime}}"
      expiredAt: "{{.expiredAt}}"
  extraPodSpec:
    {{- if .reqGpu }}
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    {{- end }
...
```
However, we encountered the issue "Bento name not found":
`events Bento 1-tf-mnist-svc--v-1-2-3 not found {"type": "Normal", "object": {"kind":"BentoDeployment","namespace":"yatai","name":"dep-bento-testirismtpl-cpu-6-1-76","uid":"d2f09f5f-3167-42ba-b67f-cacd8d99b5d1","apiVersion":"serving.yatai.ai/v2alpha1","resourceVersion":"104943704"}, "reason": "GetBento"}`

However, if we use "yatai-image-builder" for building and then deploy with the same CRD file, it works successfully.

Can we deploy using custom Docker image like we did in the previous version (1.0.0a7) without using yatai-image-builder?
