### ISSUE TITLE
Cannot access web ui

### ISSUE THREAD

**Issue by uzmargomez** [bentoml/Yatai#498]
Hey, I'm trying to install Yatai in my K8s cluster, everything seems to be working fine, but when I try to log in the web ui I get different errors. This is my `values.yaml` file (the `postgresqlcustom ` subsection contains the chart values for Bitmani's postgresql-12.1.9 helm chart)
```
postgresqlcustom:
  enabled: true
  auth:
    enablePostgresUser: false
    username: yatai
    password: password
    database: yatai

ingress:
  className: 'nginx'
  enabled: true
  hosts:
    - host: yatai.example.com
      paths:
      - /
  tls:
   - secretName: yatai-tls
     hosts:
       - yatai.example.com

postgresql:
  host: yatai-postgresqlcustom
  port: 5432
  user: yatai
  database: yatai
  sslmode: disable
  password: password
  maxOpenConns: 10
  maxIdleConns: 10
  connMaxLifetime: 15m

s3:
  endpoint: ''
  region: ''
  bucketName: ''
  secure: true
  accessKey: ''
  secretKey: ''
  accessKeyExistingSecretName: ''
  aceessKeyExistingSecretKey: 'access_key'
  secretKeyExistingSecretName: ''
  secretKeyExistingSecretKey: 'secret_key'
```

First I got errors saying the email for the admin account wasn't set up, and that it wasn't verified. I modified the "user" table in postgresql so that now it is similar to the following
```

yatai=> select * from "user";
 id |            uid            | perm  | name  | first_name | last_name |          email          | password | config | is_email_verified |          created_at           |          updated_at           | deleted_at 
----+---------------------------+-------+-------+------------+-----------+-------------------------+----------+--------+-------------------+-------------------------------+-------------------------------+------------
  1 | 65b7d.................... | admin | admin |            |           | uz@test.com             | pass1234 |        | t                 | 2024-01-29 16:30:19.426577+00 | 2024-01-29 16:30:19.426577+00 | 
```
and I no longer have the above error, but I still cannot access the UI, if I try to log in with "admin" and "pass1234" I get a message saying password is incorrect. Which credentials do I need to use as "email" and "password"? the combinations ("uz@test.com","pass1234"), ("admin","pass1234"), ("yatai","password") don't work.

Thanks in advance for any help!
