### ISSUE TITLE
Request to set the root path of the API server

### ISSUE THREAD

**Issue by skyoo2003** [bentoml/Yatai#510]
When using the URL Path rewrite function in Ingress, cannot access the dashboard page properly.
Please consider adding a features to allow access by arbitrarily specifying the root path.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app.kubernetes.io/instance: yatai
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yatai
    app.kubernetes.io/version: 1.1.13
    helm.sh/chart: yatai-1.1.13
  name: yatai
  namespace: yatai-system
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: yatai
            port:
              number: 80
        path: /yatai-console(/|$)(.*)
        pathType: ImplementationSpecific
```
